name: push to feature
on: 
  push:
    branches: demo
    
jobs:
  pmd-run: 
      runs-on: ubuntu-latest
      steps: 
      #checking out source code.
          - name: 'checkout source code'
            uses: actions/checkout@v2
            
            #install PMD
          - name: 'Install PMD'
            run: 
